### ISSUE TITLE
Need to plumb server address through

### ISSUE THREAD

**Issue by garthwebb** [tennessee-garage/ddfui#2]
There are a number of places that use localhost:port as the address for the server.  This works on devsever/local installs, but with the RPi, the client is on the laptop and the host is the RPi, so localhost calls fail.

**Comment by mik3y** [comment]
Good catch! Pushed the fix above - I should have PR'd it (little too fast on the draw). 

Here's an illustration of the fix: both UI and devserver are technically still running locally, but I'm using a `nip.io` hostname for the UI & the corresponding backend URL is used automatically.

![image](https://user-images.githubusercontent.com/390829/65651678-374bed00-dfdd-11e9-961e-e1e25c9662b9.png)
